config/routes.rb
RorGiant::Application.routes.draw do
  root 'welcome#index'
  resources :talent_requests, only: [:new, :create]
  resources :jobs, only: [:index, :show] do
    resources :job_applications,  only: :new,     to: 'jobs#jobapp'
    resources :job_applications,  only: :create,  to: 'jobs#jobapply'
    resources :job_referrals,     only: :new,     to: 'jobs#referral'
    resources :job_referrals,     only: :create,  to: 'jobs#refer'
  end
end

app/models/job.rb
class Job
  include Mongoid::Document
  has_many :job_application
  has_many :job_referral
  field :id_scheme_ext,   type: String
  field :category,        type: String
  field :title,           type: String
  field :location,        type: String
  field :employment_type, type: String
  field :start_date,      type: Date
  field :pay_rate,        type: String
  field :salary,          type: String
  field :salary_unit,     type: String
  field :description,     type: String

  def self.categories
    @@categories ||= ['ALL', 'CREATIVE', 'INTERACTIVE', 'MARKETING']
  end

  def self.category_matching(string)
    unless string.blank?
      regexp = /#{string.split[0]}/i
      self.categories.each do |category|
        return category if regexp.match category
      end
    end
    nil
  end

  def apply(attributes)
    JobApplication.build(attributes.merge!({job: self}))
  end

  def refer(attributes)
    JobReferral.create(attributes.merge!({job: self}))
  end

end

app/models/job_application.rb
class JobApplication
  include Mongoid::Document
  belongs_to :job
  field :name_first,                    type: String
  field :name_last,                     type: String
  field :email,                         type: String
  field :phone,                         type: String
  field :date_start_available,          type: Date
  field :status_employment_current,     type: String
  field :status_authorization_to_work,  type: String
  field :link_to_portfolio,             type: String
  field :link_to_resume,                type: String
  field :attachment_filename_resume,    type: String

  attr_accessor :attachment_resume, :attachment_portfolio

  def self.build(attributes)
    if (attachment_resume = attributes['attachment_resume'])
      attributes['attachment_filename_resume'] =
        attachment_resume.original_filename
      attributes.delete('attachment_resume')
    end
    if (attachment_portfolio = attributes['attachment_portfolio'])
      attributes['attachment_filename_portfolio'] =
        attachment_portfolio.original_filename
      attributes.delete('attachment_portfolio')
    end
    JobApplication.create(attributes).tap do |obj|
      obj.attachment_resume    = attachment_resume
      obj.attachment_portfolio = attachment_portfolio
    end
  end

  def name
    name_first.empty? ? name_last :
      (name_first + (name_last.empty? ? "" :
                    (" " + name_last)))
  end
end

app/models/job_referral.rb
class JobReferral
  include Mongoid::Document
  belongs_to :job
  field :email,   type: String
  field :name,    type: String
  field :subject, type: String
  field :body,    type: String
end

app/models/talent_request.rb
class TalentRequest
  include Mongoid::Document
  field :name,      type: String
  field :company,   type: String
  field :email,     type: String
  field :phone,     type: String
  field :what,      type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:jobapp, :jobapply, :referral, :refer]
  respond_to :html, :js

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Rails.application.jobs_facility.refresh_jobs(category: params[:category])
  end

  # GET /jobs/1/jobapp
  def jobapp
    @jobapp = JobApplication.new
  end

  # POST /jobs/1/jobapply
  def jobapply
    if params[:commit].eql?('SEND')
      if @job
        if (job_application = @job.apply(params.require(:job_application).permit!))
          AppMailer.mail_application(job_application).deliver
        end
      end
    end
  end

  # GET /jobs/1/referral
  def referral
    @referral = JobReferral.new
  end

  # POST /jobs/1/refer
  def refer
    if params[:commit].eql?('SEND')
      if @job
        if (job_referral = @job.refer(params.require(:job_referral).permit!))
          AppMailer.mail_referral(job_referral).deliver
        end
      end
    end
  end

  private
    def set_job
      @job = Job.find(params[:job_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :identification, :location, :work_schedule, :start_date, :pay_rate, :description)
    end
end

app/controllers/talent_requests_controller.rb
class TalentRequestsController < ApplicationController
  def new
    @talent_request = TalentRequest.new
  end

  def create
=begin @@@ FUTURE WORK
    @talent_request = TalentRequest.new(params.require(:talent_request).permit!))
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
    respond_with
=end
    if (talent_request = TalentRequest.create(params.require(:talent_request).permit!))
      AppMailer.mail_talent_request(talent_request).deliver
    end
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_button_contact_us.erb
<%= link_to "Let's Get Started -- Contact Us!", page_path(id: 'contact'), class: 'giant-button-contact-us' %>

app/views/application/_button_open_jobs.erb
<%= link_to 'Open Jobs', jobs_path , class: 'giant-button-open-jobs' %>

app/views/application/_button_request_talent.erb
<%= link_to 'Request Talent', new_talent_request_path , class: 'giant-button-request-talent' %>

app/views/application/_caption_substance.html.erb
    <div class="giant-section-substance-caption-all-div">
       <div class="giant-section-substance-caption-tab-div">
         <img src="/assets/giant-roles-tab.png"></img>
       </div>
      <h2 class="giant-section-substance-caption-text-heading">
        <%= text %>
      </h2>
    </div>

app/views/application/_footer.html.erb
<footer class="giant-footer">
  <div class="giant-footer-container-div">
    <div class="giant-footer-row-div">
      <ul>
        <li>
          <a href="<%= Rails.application.config.custom_link_facebook %>">
            <img src="/assets/FB-f-Logo__white_144.png"/>
          </a>
        </li>
        <li>
          <a href="<%= Rails.application.config.custom_link_twitter %>">
            <img src="/assets/Twitter_logo_white.png"/>
          </a>
        </li>
        <li>
          <a href="<%= Rails.application.config.custom_link_linkedin %>">
            <img src="/assets/In-White-128px-R.png"/>
          </a>
        </li>
      </ul>
    </div>
    <div class="giant-footer-row-div">
      <p>&copy GIANT 2017</p>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<header>
  <div class="giant-header-div">
    <nav>
      <div class="giant-nav-container-div">
        <div class="giant-nav-menu-toggle-outer-div">
          <div class="giant-nav-menu-toggle-inner-div">
            <button data-toggle="collapse" data-target="#giant-nav-contents-collapsable">
              <span class="giant-toggle-assist-span">toggle navigation</span>
              <div class="giant-nav-menu-hamburger-div">
                <span class="giant-hamburger-layer-span"></span>
                <span class="giant-hamburger-layer-span"></span>
                <span class="giant-hamburger-layer-span"></span>
              </div>
            </button>
          </div>
        </div>
        <div class="giant-nav-contents-always-outer-div">
          <div class="giant-nav-contents-always-inner-div">
            <a href="/"><span class="giant-brand-span"></span></a>
            <h2 class="giant-tagline-h2">RECRUITING FOR USER EXPERIENCE + CREATIVE + MARKETING</h2>
            <h2 class="giant-phone-number-h2">415.366.8855</h2>
          </div>
        </div>
        <div class="giant-nav-contents-collapsable-div" id="giant-nav-contents-collapsable">
          <div class="giant-nav-menu-div">
            <ul>
              <li><a href="/pages/clients">FOR CLIENTS</a></li>
              <li><a href="/pages/candidates">FOR CANDIDATES</a></li>
              <li><a href="/jobs">OPEN JOBS</a></li>
              <li><a href="/pages/contact">CONTACT US</a></li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/application/_job.html.erb
<div class="giant-job" id="<%= @job.id_scheme_ext %>">
  <% if local_assigns.has_key?(:including) && including.include?(:category) %>
    <div class="giant-section-substance-jobs-category-div">
        <%= render './application/job_category' %>
    </div>
  <% end %>
  <%= render './application/job_details' %>
</div>

app/views/application/_job_category.html.erb
      <%  Job.categories.each_with_index do |cat, i| %>
        <%  if i > 0 %>
              |
        <%  end %>
        <%  if (iscat = (@job && @job.category == cat)) %>
              <strong>
        <%  end %>
        <%= link_to cat, jobs_path(category: cat), class: 'giant-section-substance-jobs-category-text' %>
        <%  if iscat %>
              </strong>
        <%  end %>
      <%  end %>

app/views/application/_job_details.html.erb
<div class="giant-section-substance-jobs-details-all-div">
  <div class="giant-section-substance-jobs-details-brief-div">
    <div class="giant-section-substance-jobs-details-brief-content-div">
      <p class="giant-section-substance-jobs-details-brief-content-number-p">
        <span class="giant-section-substance-jobs-details-brief-content-number-label-span">
          JOB
        </span>
        <span class="giant-section-substance-jobs-details-brief-content-number-digits-span">
          #<%= @job.id_scheme_ext %>
        </span>
      </p>
      <p class="giant-section-substance-jobs-details-brief-content-title-p">
        <%= @job.title %>
      </p>
<!-- !!! disabled, so now these details must be provided in the decription below
  <h4><strong>LOCATION:</strong>  <%= @job.location %></h4>
  <h4><strong>STATUS:</strong>    <%= @job.employment_type %></h4>
  <h4><strong>STARTS:</strong>    <%= @job.start_date %></h4>
  <h4><strong>RATE:</strong>      <%= @job.pay_rate %></h4>
  <br>
-->
    </div>
    <div class="giant-section-substance-jobs-details-brief-line-outer-div">
      <div class="giant-section-substance-jobs-details-brief-line-inner-div">
        &nbsp;
      </div>
    </div>
  </div>
  <div class="giant-section-substance-jobs-details-description-div">
    <%= render './jobs/jobapp_hidden' %>
    <%= render './jobs/referral_hidden' %>
    <div class="giant-section-substance-jobs-details-description-prose-div">
      <p><%= raw @job.description %>
        <!--%= link_to 'MORE', @job %-->
      </p>
    </div>
  </div>
</div>

app/views/application/_section_jumbo.html.erb
<div class="giant-section-logos-all-div">
  <div class="group-first-div">
    <div class="img-div"><img src="/assets/giant-logo-bbdo.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-solarcity.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-fitbit.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-ubisoft.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-sumologic.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-uber.svg"/></div>
  </div>
  <div class="group-second-div">
    <div class="img-div"><img src="/assets/giant-logo-sephora.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-riverbed.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-rh.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-shaklee.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-tibco.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-publicis.svg"/></div>
  </div>
</div>

app/views/application/_section_logos.html.erb
<div class="giant-section-logos-all-div">
  <div class="group-first-div">
    <div class="img-div"><img src="/assets/giant-logo-bbdo.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-solarcity.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-fitbit.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-eventbrite-10pct.png"/></div>
    <div class="img-div"><img src="/assets/giant-logo-sumologic.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-uber.svg"/></div>
  </div>
  <div class="group-second-div">
    <div class="img-div"><img src="/assets/giant-logo-sephora.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-riverbed.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-rh.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-shaklee.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-tibco.svg"/></div>
    <div class="img-div"><img src="/assets/giant-logo-publicis.svg"/></div>
  </div>
</div>

app/views/application/_substance_caption_tab.html.erb
<div class="giant-section-substance-caption-tab-div">
  <img src="/assets/giant-roles-tab.png"></img>
</div>

app/views/application/_substance_caption_text.html.erb
<div class="giant-section-substance-caption-all-div">
  <%= render partial: 'substance_caption_tab' %>
  <h2 class="giant-section-substance-caption-text-heading">
    <%= text %>
  </h2>
</div>

app/views/jobs/_details.html.erb
<div class="giant-job" id="<%= @job.id_scheme_ext %>">
  <h4>
    <%  Job.categories.each_with_index do |cat, i| %>
      <%  if i > 0 %>
            &nbsp;|&nbsp;
      <%  end %>
      <%  if (iscat = (@job.category == cat)) %> 
            <strong>
      <%  end %>
      <%= cat %>
      <%  if iscat %> 
            </strong>
      <%  end %>
    <%  end %>
  </h4>
  <h3>                            <%= @job.title %></h3>
  <h4><strong>JOB#</strong>       <%= @job.id_scheme_ext %></h4>
  <br>
  <h4><strong>LOCATION:</strong>  <%= @job.location %></h4>
  <h4><strong>STATUS:</strong>    <%= @job.employment_type %></h4>
  <h4><strong>STARTS:</strong>    <%= @job.start_date %></h4>
  <h4><strong>RATE:</strong>      <%= @job.pay_rate %></h4>
  <br>
  <p><%= raw @job.description %>
    <!--%= link_to 'MORE', @job %-->
  </p>
</div> <!-- /giant-job -->

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.text_field :identification %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :work_schedule %><br>
    <%= f.text_field :work_schedule %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :pay_rate %><br>
    <%= f.text_field :pay_rate %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_jobapp.html.erb
<div class="giant-section-substance-jobs-disposition-all-div">
  <hr class="giant-hr-top">
  <h2>APPLY</h2>
  <%= form_for([@job, @jobapp], html: {multipart: true}, remote: true) do |f| %>
    <%= token_tag(nil) %>
    <% if @jobapp.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@jobapp.errors.count, "error") %> prohibited this job from being saved:</h2>
        <ul>
        <% @jobapp.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :name_first, class: "giant-jobapp-name-first-input",
        placeholder: "First Name*" %>
    <div class="giant-jobapp-employment-div">
      <%= f.select :status_employment_current,
          ['Employed', 'Self-Employed', 'Unemployed', 'Student'],
          {prompt: "Current Employment Status"},
          {class: "giant-jobapp-employment-select"} %>
    </div>
    <%= f.text_field :name_last, class: "giant-jobapp-name-last-input",
        placeholder: "Last Name*" %>
    <div class="giant-jobapp-authorized-div">
      <%= f.select :status_authorization_to_work,
          ['Yes', 'Visa Transfer', 'No'],
          {prompt: "Authorized to work in the US?"},
          {class: "giant-jobapp-authorized-select"} %>
    </div>
    <%= f.text_field :email, class: "giant-jobapp-email-input",
        placeholder: "Email*" %>
    <%= f.text_field :link_to_portfolio, class: "giant-jobapp-portfolio-link-input",
        placeholder: "Add link to portfolio (if applicable)" %>
    <%= f.text_field :phone, class: "giant-jobapp-phone-input",
        placeholder: "Phone*" %>
    <%= f.text_field :link_to_resume, class: "giant-jobapp-resume-link-input",
        placeholder: "Add link to resume" %>
    <div class="giant-jobapp-available-div">
      <%= f.label "Available Start Date:" %>
      <%= f.date_field :date_start_available, class: "giant-jobapp-available-input-date",
          placeholder: "MM/DD/YYYY" %>
    </div>
    <div class="giant-jobapp-resume-file-div">
      <span class=giant-jobapp-resume-file-pre-span>Attach resume:</span>
      <label class="giant-jobapp-resume-file-label">
        <%= f.file_field :attachment_resume, class: "giant-jobapp-resume-file-input" %>
        <span class=giant-jobapp-resume-file-post-span>choose file</span>
      </label>
    </div>
  <hr class="giant-hr-bottom">
  <div class="giant-referral-submits-div">
    <%= f.submit 'x CANCEL', name: 'cancel', class: 'giant-referral-submit-cancel-input' %>
    <%= f.submit 'SEND', class: 'giant-referral-submit-send-input' %>
  </div>
  <% end %>
</div>

app/views/jobs/_jobapp_hidden.html.erb
<div id="<%= @job.id_scheme_ext %>_jobapp" style="display:none;">
</div>

app/views/jobs/_jumbotron.erb
  <div class="giant-jumbo-all-div">
    <div class="giant-jumbo-image-div giant-background-jumbo-jobs">
        <%= render partial: "section_logos" %>
    </div>
    <div class="giant-jumbo-content-div giant-jumbo-content-offset-jobs">
      <h1 class="giant-jumbo-text-breaks1">
          TAKE THE NEXT STEP.<br>
          WE'VE GOT YOU COVERED.
      </h1>
      <h1 class="giant-jumbo-text-breaks2">
          TAKE THE NEXT<br>
          STEP. WE'VE GOT<br>
          YOU COVERED.
      </h1>
    </div>
  </div>

app/views/jobs/_referral.html.erb
<div class="giant-section-substance-jobs-disposition-all-div">
  <hr class="giant-hr-top">
  <h2>TELL A FRIEND</h2>
  <%= form_for([@job, @referral], remote: true) do |f| %>
    <% if @referral.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@referral.errors.count, "error") %> prohibited this job from being saved:</h2>
        <ul>
        <% @referral.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :name, class: "giant-referral-friends-name-input",
        placeholder: "Friend's Name*" %>
    <%= f.text_field :email, class: "giant-referral-friends-email-input",
        placeholder: "Friend's Email*" %>
    <%= f.text_field :subject, class: "giant-referral-subject-input",
        value: "Giant Job Listing: #{@job.title} - JOB ##{@job.id_scheme_ext}" %>
    <%= f.text_area :body, cols:80, rows:6, class: "giant-referral-body-input",
        value: "Hello! I found an open role you might be interested in, courtesy of Giant Recruiting." %>
  <hr class="giant-hr-bottom">
  <div class="giant-referral-submits-div">
    <%= f.submit 'x CANCEL', name: 'cancel', class: 'giant-referral-submit-cancel-input' %>
    <%= f.submit 'SEND', class: 'giant-referral-submit-send-input' %>
  </div>
  <% end %>
</div>

app/views/jobs/_referral_hidden.html.erb
<div id="<%= @job.id_scheme_ext %>_referral" style="display:none;">
</div>

app/views/jobs/index.html.erb
<%= render partial: 'header', locals: { tab:@virtual_path[/^[^\/]+/] } %>
<div class="giant-section-aggregate-div">
  <%= render partial: 'jumbotron' %>
  <div class="giant-section-substance-all-div">
    <div class="giant-section-substance-caption-all-div">
        <%= render partial: 'substance_caption_tab' %>
    </div>
    <div class="giant-section-substance-jobs-bundle-div">
    <% if @jobs.empty? %>
      <div class="giant-section-substance-jobs-category-div">
          <%= render 'job_category' %>
      </div>
    <% else %>
      <% @jobs.each do |job| %>
        <% @job = job %>
        <%= render 'job', including: [:category] %>
        <div class="giant-section-substance-jobs-buttons-div">
          <%= link_to 'TELL A FRIEND', new_job_job_referral_path(@job),     remote: true, class: 'giant-section-substance-jobs-button' %>
          <%= link_to 'APPLY',         new_job_job_application_path(@job),  remote: true, class: 'giant-section-substance-jobs-button' %>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<%= render partial: 'footer' %>

app/views/jobs/jobapp.js.erb
$('#<%= @job.id_scheme_ext %>_jobapp').html("<%= j (render 'jobapp') %>");
$('#<%= @job.id_scheme_ext %>_jobapp').slideDown(350);

app/views/jobs/jobapply.js.erb
$('#<%= @job.id_scheme_ext %>_jobapp').html("<%= j (render 'jobapp_hidden') %>");
$('#<%= @job.id_scheme_ext %>_jobapp').slideDown(350);

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/refer.js.erb
$('#<%= @job.id_scheme_ext %>_referral').html("<%= j (render 'referral_hidden') %>");
$('#<%= @job.id_scheme_ext %>_referral').slideDown(350);

app/views/jobs/referral.js.erb
$('#<%= @job.id_scheme_ext %>_referral').html("<%= j (render 'referral') %>");
$('#<%= @job.id_scheme_ext %>_referral').slideDown(350);

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<% job = @job %>
<%= render 'job' %>
<%= render 'buttons' %>

<%= link_to 'Edit', edit_job_path(@job),  class: 'giant-button' %> |
<%= link_to 'Back', jobs_path,            class: 'giant-button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- BEGIN bootstrap required prefix -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- END bootstrap required prefix -->
  <title>Giant Recruiting</title>
  <!-- @@@ THIS DOESN'T WORK WITH MULTI-RES *.ico @@@ favicon_link_tag '/favicon.ico' -->
  <%= favicon_link_tag '/logo/logo-g-square-shrunk4-x016-y016.png', type: 'image/png' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/candidates.html.erb
<%= render partial: 'header', locals: {tab: @virtual_path[/^[^\/]+/]} %>
<div class="giant-section-aggregate-div">
  <div class="giant-jumbo-all-div">
    <div class="giant-jumbo-image-div giant-background-jumbo-candidates">
        <%= render partial: "section_logos" %>
    </div>
    <div class="giant-jumbo-content-div giant-jumbo-content-offset-candidates">
      <h1 class="giant-jumbo-text-breaks1">
          GREATNESS AWAITS.<br>
          WE'LL GET YOU THERE.
      </h1>
      <h1 class="giant-jumbo-text-breaks2">
          GREATNESS<br>
          AWAITS. WE'LL<br>
          GET YOU THERE.
      </h1>
      <div class="giant-jumbo-buttons-div">
        <%= render partial: "button_open_jobs" %>
      </div>
    </div>
  </div>
  <div class="giant-section-substance-all-div">
    <%= render partial: 'substance_caption_text', locals: { text:'WHY TOP CANDIDATES CHOOSE GIANT' } %>
    <div class="giant-substance-cluster-div">
      <div class="giant-substance-cluster-item-div">
        <h4>THE RIGHT POSITION</h4>
        <p>We have the right position for you.
          We'll take the time to understand your career goals
          and objectives, so we can match you to your dream job.</p>
      </div>
      <div class="giant-substance-cluster-item-div">
        <h4>UNDERSTANDING EMPLOYER NEEDS</h4>
        <p>We understand what employers are looking for.
          We'll guide you every step of the way and match you with
          the right opportunities to advance your career.</p>
      </div>
      <div class="giant-substance-cluster-item-div">
        <h4>COMPENSATION INSIGHT</h4>
        <p>We know compensation inside out.
          Our compensation experts will advise you on market rates
          and trends so you know you'll get what you're worth.</p>
      </div>
    </div>
    <div class="giant-substance-cluster-div">
      <div class="giant-substance-cluster-item-div">
        <h4>INTERVIEW PREPARATION</h4>
        <p>We set you up for success.
          We have valuable insight into the hiring managers interview
          process and we'll prep you before your interviews to make
          sure your'e a step ahead.</p>
      </div>
      <div class="giant-substance-cluster-item-div">
        <h4>MAKING YOU STAND OUT</h4>
        <p>We want you to be your best.
          Out experienced recruiting team will guide you whether
          advising on your resume, portfolio or how to achieve your
          career goals.</p>
      </div>
      <div class="giant-substance-cluster-item-div">
        <h4>PROACTIVE OUTREACH</h4>
        <p>We move fast.
          Even if we don't have an open job that's a fit, we'll
          proactively reach out to employers for opportunities
          that align with your career objectives.</p>
      </div>
    </div>
    <div class="giant-substance-cluster-div">
      <div class="giant-substance-cluster-full-link-div">
        <%= render partial: "button_contact_us" %>
      </div>
    </div>
    <div class="giant-substance-cluster-div">
      <div class="giant-substance-cluster-testimonial-div">
        <blockquote>
          “The Giant Recruiting team is amazing! They are great at
          communicating and getting results. Always available
          for questions and advice. I have worked with them on
          several freelance gigs and would highly recommend
          anyone thinking of using a professional recruiter to
          contact Giant Recruiting!!”
        <footer><cite>
          - Mark P., Sr. Product Manager
        </cite></footer>
        </blockquote>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'footer' %>